version: '3.5'

services:
  balancer:
    image: haproxy
    container_name: balancer
    restart: always
    ports:
      - 443:443
    volumes:
      - /root/volume/balancer/app/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - frontend
  drive_proxy:
    image: nginx
    container_name: drive_proxy
    restart: always
    volumes:
      - /root/volume/drive/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /root/volume/drive/proxy/ssl:/etc/ssl/nginx
    networks:
      - frontend
      - backend
  drive_app:
    image: nextcloud
    container_name: drive_app
    restart: always
    volumes:
      - /root/volume/drive/app:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
  drive_redis:
    image: redis
    container_name: drive_redis
    restart: always
    command: redis-server --requirepass <password>
    networks:
      - backend
  elestilolibre_proxy:
    image: nginx
    container_name: elestilolibre_proxy
    restart: always
    volumes:
      - /root/volume/elestilolibre/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /root/volume/elestilolibre/proxy/ssl:/etc/ssl/nginx
    networks:
      - frontend
      - backend
  elestilolibre_app:
    image: wordpress
    container_name: elestilolibre_app
    restart: always
    volumes:
      - /root/volume/elestilolibre/app:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

networks:
  frontend:
    name: frontend
  backend:
    name: backend
    ipam:
      config:
        - subnet: 192.168.3.0/24