version: '3.5'

services:
  drive_proxy:
    image: nginx
    container_name: drive_proxy
    restart: always
    volumes:
      - /root/volume/drive/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /root/volume/drive/proxy/ssl:/etc/ssl/nginx
    ports:
      - 20001:443
  drive_app:
    image: nextcloud
    container_name: drive_app
    restart: always
    volumes:
      - /root/volume/drive/app:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
  drive_redis:
    image: redis
    container_name: drive_redis
    restart: always
    command: redis-server --requirepass <redis_pass>