version: "3.5"

services:
  app:
    image: wordpress
    container_name: elestilolibre_app
    restart: always
    volumes:
      - /share/docker/elestilolibre/app:/var/www/html
    ports:
      - 20000:80
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elestilolibre.rule=Host(`elestilolibre.com`)"
      - "traefik.http.routers.elestilolibre.entrypoints=https"
      - "traefik.http.routers.elestilolibre.tls=true"
  db:
    image: mysql
    container_name: elestilolibre_db
    restart: always
    volumes:
      - /share/docker/elestilolibre/db/conf/my.cnf:/etc/my.cnf
      - /share/docker/elestilolibre/db/mysql:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    name: backend