version: "3.5"

services:
  app:
    image: hurlenko/filebrowser
    container_name: filebrowser_app
    user: "${UID}:${GID}"
    volumes:
      - /share/docker/filebrowser/app/data:/data
      - /share/docker/transmission/app/downloads/complete:/data/torrent
      - /share/docker/filebrowser/app/config:/config
    environment:
      - FB_BASEURL=/
    restart: always
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`upload.rimtu.com`)"
      - "traefik.http.routers.filebrowser.entrypoints=https"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
networks:
  backend:
    name: backend