version: "3.5"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /share/docker/plex/app/library:/config
      - /share/docker/plex/app/tvseries:/tv
      - /share/docker/plex/app/movies:/movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.rimtu.com`)"
      - "traefik.http.routers.plex.entrypoints=https"
      - "traefik.http.routers.plex.tls.certresolver=letsencrypt"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    networks:
      - backend
networks:
  backend:
    name: backend