version: "3.5"

services:
  app:
    image: lscr.io/linuxserver/transmission
    container_name: transmission_app
    restart: unless-stopped
    volumes:
      - /share/docker/transmission/app/data:/config
      - /share/docker/transmission/app/downloads:/downloads
      - /share/docker/transmission/app/watch:/watch
    networks:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`torrent.rimtu.local`)"
      - "traefik.http.routers.transmission.entrypoints=https"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
networks:
  backend:
    name: backend