version: "3.5"

services:
  urbackup:
    image: uroni/urbackup-server:latest
    container_name: urbackup
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /share/docker/urbackup/app/database:/var/urbackup
      - /share/docker/urbackup/app/backups:/backups
    ports:
      - 55413:55413
      - 55414:55414
      - 55415:55415
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.urbackup.rule=Host(`urbackup.rimtu.local`)"
      - "traefik.http.routers.urbackup.entrypoints=https"
      - "traefik.http.routers.urbackup.tls=true"
      - "traefik.http.services.urbackup.loadbalancer.server.port=55414"
    networks:
      - backend
networks:
  backend:
    name: backend