version: '3.5'

services:
  router_proxy:
    image: nginx
    container_name: elestilolibre_proxy
    restart: always
    volumes:
      - /share/docker/proxy/app/default.conf:/etc/nginx/templates/default.conf.template
      - /share/docker/proxy/app/ssl/elestilolibre:/etc/ssl/nginx
    environment:
      - BACKEND_PROTOCOL=http
      - BACKEND_HOST=elestilolibre_app
      - BACKEND_PORT=80
      - CLIENT_MAX_BODY_SIZE=0
    networks:
      - frontend
      - backend
  app:
    image: wordpress
    container_name: elestilolibre_app
    restart: always
    volumes:
      - /share/docker/elestilolibre/app:/var/www/html
    networks:
      - backend
  db:
    image: mysql
    container_name: elestilolibre_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - /share/docker/elestilolibre/db:/var/lib/mysql
    networks:
      - backend
networks:
  frontend:
    name: frontend
  backend:
    name: backend