version: "3.5"

services:
  proxy:
    image: nginx
    container_name: portainer_proxy
    restart: always
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/ssl:/etc/ssl/nginx
    networks:
      - frontend
      - backend
  app:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./app/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:9000
    networks:
      - backend
networks:
  frontend:
    name: frontend
  backend:
    name: backend