version: '3.5'

services:
  drive_app:
    image: nextcloud
    container_name: drive_app
    restart: always
    volumes:
      - /root/volume/drive/app:/var/www/html
    ports:
      - 20001:80
  drive_redis:
    image: redis
    container_name: drive_redis
    restart: always
    command: redis-server --requirepass <redis_pass>