version: '3.5'

services:
  balancer:
    image: haproxy
    container_name: balancer
    restart: always
    ports:
      - 443:443
    volumes:
      - /root/volume/balancer/app/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg