version: '3.5'

services:
  elestilolibre_proxy:
    image: nginx
    container_name: elestilolibre_proxy
    restart: always
    volumes:
      - /root/volume/elestilolibre/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /root/volume/elestilolibre/proxy/ssl:/etc/ssl/nginx
    ports:
      - 20000:443
  elestilolibre_app:
    image: wordpress
    container_name: elestilolibre_app
    restart: always
    volumes:
      - /root/volume/elestilolibre/app:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"